name: e_commerce_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"

dependencies:
  flutter:
    sdk: flutter
  search_app_bar_page: ^2.5.0
  google_fonts:
  provider: ^6.1.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    # - assets/icons/user.png
    # - assets/icons/home.png
    # - assets/icons/heart.png
    # - assets/icons/shopping-cart.png
    # - assets/icons/search.png
    # - assets/icons/drawer.png
    # - assets/icons/hand-wave.png
    # - assets/icons/watch-smart.png
    # - assets/icons/tshirt.png
    # - assets/icons/bag.png
    # - assets/icons/boot.png
    # - assets/icons/glasses.png
    # - assets/icons/settings.png
    # - assets/icons/info.png
    # - assets/icons/messages.png
    # - assets/icons/contrast.png
    # - assets/icons/language.png

    - assets/images/
    # - assets/images/ads1.png
    # - assets/images/ads2.png
    # - assets/images/ads3.png

    - assets/products/tshirts/
    # - assets/products/tshirts/t-shirt1.png
    # - assets/products/tshirts/t-shirt2.png
    # - assets/products/tshirts/t-shirt3.png
    # - assets/products/tshirts/t-shirt4.png
    # - assets/products/tshirts/t-shirt5.png
    # - assets/products/tshirts/t-shirt6.png

    - assets/products/watches/
    # - assets/products/watches/apple-watch11.png
    # - assets/products/watches/galaxy-watch-ultra.png
    # - assets/products/watches/galaxy-watch7.png
    # - assets/products/watches/apple-watch-se.png
    # - assets/products/watches/pixel-watch.png
    # - assets/products/watches/huawei-watch.png

    - assets/products/bags/
    # - assets/products/bags/bag1.png
    # - assets/products/bags/bag2.png
    # - assets/products/bags/bag3.png
    # - assets/products/bags/bag4.png
    # - assets/products/bags/bag5.png
    # - assets/products/bags/bag6.png

    - assets/products/boots/
    # - assets/products/boots/boots1.png
    # - assets/products/boots/boots2.png
    # - assets/products/boots/boots3.png
    # - assets/products/boots/boots4.png
    # - assets/products/boots/boots5.png
    # - assets/products/boots/boots6.png